// app/lib/constants.ts

export const TECH_TAGS = [
  "Android",
  "AWS",
  "BSP",
  "C/C++",
  "Cloud Services",
  "DevOps",
  "Embedded Systems",
  "Firmware",
  "Full Stack",
  "Golang",
  "Hardware Bringup",
  "Infrastructure",
  "IoT",
  "Java",
  "JavaScript",
  "Kotlin",
  "Linux Kernel",
  "Mobile Development",
  "Open Source",
  "Prototyping",
  "Python",
  "Qualcomm Snapdragon",
  "React",
  "Rust",
  "System Architecture",
  "Team Leadership",
];
