// app/lib/constants.ts

export const TECH_TAGS = [
  'AI/ML',
  'Android',
  'AWS',
  'Backend',
  'BSP',
  'C/C++',
  'Cloud Native',
  'DevOps',
  'Embedded',
  'Firmware',
  'Frontend',
  'Full Stack',
  'Golang',
  'Hardware Bringup',
  'Infrastructure',
  'IoT',
  'Java',
  'JavaScript',
  'Kotlin',
  'Kubernetes',
  'Linux Kernel',
  'Mobile',
  'Node.js',
  'Open Source',
  'Prototyping',
  'Python',
  'Qualcomm Snapdragon',
  'React',
  'Rust',
  'System Architecture',
  'Team Leadership',
  'TypeScript',
]
